kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit-rb
subjects:
  - kind: ServiceAccount
    name: api-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-edit
