kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: api-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Source