kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - configmaps
      - imagestreams
  - verbs:
      - list
    apiGroups:
      - 'image.openshift.io'
    resources:
      - imagestreams
